- type: replace
  path: /releases?/name=slack-notifications?
  value:
    name:    slack-notification-resource
    version: 9
    sha1:    a64c65d1f23ea089746e698f29dbe522dd716c1b
    url:     https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
