# Jobs used in the small-footprint and full deployments. Base jobs
# are still located in base.yml
---
meta:
  jobs:
    haproxy:  
      release: haproxy
      properties:
        ha_proxy:
          tcp:
            - name: web_http
              port: 80
              backend_port: 8080
              backend_servers: (( grab instance_groups.web.networks.0.static_ips || instance_groups.concourse.networks.0.static_ips ))

    bpm:
      release: bpm

    web:
      release: concourse
      properties:
        worker_gateway:
          host_key:
            private_key: (( vault meta.vault "/tsa/host_key:private" ))
            public_key: (( vault meta.vault "/tsa/host_key:public" ))
          authorized_keys:
          - (( vault meta.vault "/tsa/worker_key:public" ))
        postgresql:
          database: atc
          role:
            name: atc
            password: (( vault meta.vault "/database/atc:password" ))
        token_signing_key: (( grab params.token_signing_key ))
        bind_port: 8080
        publicly_viewable: true
        main_team:
          auth:
            local:
              users:
                - (( grab params.main_user || meta.default.main_user ))
        add_local_users:
          - (( concat meta.jobs.web.properties.main_team.auth.local.users.0 ":" meta.http_auth_password ))
        external_url: (( grab params.external_url ))
        
    postgres:
      release: postgres
      properties:
        databases:
          port: 5432
          databases:
          - name: atc
          roles:
          - name: atc
            password: (( vault meta.vault "/database/atc:password" ))
    locker:
      release: locker
      properties:
        locker:
          user: locker
          password: (( vault meta.vault "/locker/api:password" ))
          ssl_cert: (( vault meta.vault "/locker/server:certificate" ))
          ssl_key: (( vault meta.vault "/locker/server:key" ))
    worker:
      release: concourse
      properties:
        http_proxy_url:  (( grab params.http_proxy  || "" ))
        https_proxy_url: (( grab params.https_proxy || "" ))
        no_proxy:        (( grab params.no_proxy    || meta.default.no_proxy ))
        worker_gateway:
          registration_mode: forward
          worker_key:
            private_key: (( vault meta.vault "/tsa/worker_key:private" ))
            public_key: (( vault meta.vault "/tsa/worker_key:public" ))
        baggageclaim:
          driver: (( grab params.volume_driver ))

  http_auth_password: (( vault meta.vault "/webui:password-bcrypt" ))
